version: '3'
services:
  geodata-extractor-fe:
    image: registry.ecosystem-urbanage.eu/geodata-extractor-fe:main
    build:
      context: .
      args:
        BASE_HREF: /
    ports:
      - '80:80'
    volumes:
      - ./src/assets/config.json:/usr/share/nginx/html/assets/config.json
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - geodata-extractor-network


networks:
  geodata-extractor-network:
    driver: bridge